## 사이킷런 프레임워크 익히기

In [ ]:
# 사이킷런 라이브러리 다운로드
!pip install scikit-learn==1.5.1

# 라이브러리 설치 확인
import sklearn
print(sklearn.__version__)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 16.5 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
1.5.1


In [ ]:
import sklearn
from sklearn.datasets import load_iris
# iris  데이터셋 import


# 붓꽃 데이터 세트를 로딩합니다.
iris_data = load_iris()

# bunch 데이터 타입은 파이썬의 딕셔너리와 유사합니다.
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
# 붓꽃 데이터 세트에 어떠한 키들이 있는지 확인합니다.
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
# 붓꽃 데이터 세트의 feature들 확인
print('\n feature_names 의 type:', type(iris_data.feature_names))
print(' feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

# 붓꽃 데이터 세트의 target이 무엇인지 확인
print('\n target_names 의 type:',type(iris_data.target_names))
print(' feature_names 의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

# 전체 data의 데이터타입과 구조, 저장된 값 확인
print('\n data 의 type:',type(iris_data.data))
print(' data 의 shape:',iris_data.data.shape)
print(iris_data['data'])

# target 데이터의 데이터 타입, 형태, 저장된 값 확인
print('\n target 의 type:',type(iris_data.target))
print(' target 의 shape:',iris_data.target.shape)
print(iris_data.target)

# feature = 우리가 학습시킬 자료.
# dataframe에서 하나의 column

# target = 우리가 목표로 하는 정답지
# feature을 가지고 학습시켜서 target을 예측(분류)하는 것을 목표로 함.


 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type: <class 'numpy.ndarray'>
 feature_names 의 shape: 3
['setosa' 'versicolor' 'virginica']

 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0

## 붓꽃(Iris) 데이터 품종 예측하기

In [ ]:
# 데이터 로드 라이브러리
from sklearn.datasets import load_iris
# 모델 업로드(의사결정 트리 분류기)
from sklearn.tree import DecisionTreeClassifier
# 학습 데이터 / 테스트데이터 분리 코드
from sklearn.model_selection import train_test_split
import pandas as pd

# 붓꽃 데이터 세트를 로딩합니다.
iris = load_iris()

# iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target
print('iris target값:', iris_label)

# iris target명 확인 0='setosa', 1='versicolor', 2='virginica'
print('iris target명:', iris_data.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환합니다.
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


AttributeError: 'numpy.ndarray' object has no attribute 'target_names'

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# DecisionTreeClassifier 객체 생성
# 무작위로 조건을 mapping, 랜덤 시드를 고정할 수 있음.
dt_clf = DecisionTreeClassifier(random_state=11)
#model = DecisionTreeClassifier()

# 모델 학습 시작
dt_clf.fit(iris_data, iris_label)

# 학습 데이터 셋으로 예측 수행
pred = dt_clf.predict(iris_data)

# 예측 정확도를 구하기 위한 accuracy_score import
from sklearn.metrics import accuracy_score
#                                    정답지,   예상답안
print('예측 정확도:',accuracy_score(iris_label, pred))

# 가지고 있는 정답 데이터 대비, 예측한 답안이 얼마나 맞았는지 비율

예측 정확도: 1.0


### train_test_split
전체 데이터를 tarin, test 데이터로 분리하는 과정이 필요하다.

In [ ]:
# data, label을 train, test 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state =11)
#학습용_data, 테스트용_data, 학습용_target, 테스트용_target = train_test_split(iris_data, iris_label, test_size = 0.2, ranmdom_state=11)

# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)

# 에측해보기
from sklearn.metrics import accuracy_score
print('예측 정확도: {0: .4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:  0.9333
